name: First Workflow #name of the workflow
on: workflow_dispatch #the event(s) that should trigger this workflow
jobs: 
  first-job: 
    runs-on: ubuntu-latest #environment where the steps within a job should be executed
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - bye!"


